### ISSUE TITLE
Future Feature Additions

### ISSUE THREAD

**Issue by pdwaggoner** [pdwaggoner/hhi#4]
## TODO for `hhi`:

* [x] more flexible plotting options
* [ ] expanded calculations (e.g., normalized (and generalized) hhi calculations
* [ ] measures of uncertainty (SEs and CIs)
